# -*- coding: utf-8 -*-
"""api

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pMnfNcOhbAX3iJJUWC83PGkz3sTqQVEO
"""

#導入模組
import requests
import pandas as pd

#連接網站、獲取網頁內容
url = "https://data.moenv.gov.tw/api/v2/aqx_p_434?format=json&api_key=d219795b-7317-4700-a476-f7a94e63a6df"
response = requests.get(url)

dic = response.json() #轉成字典
records = dic["records"] #從字典裡把records欄位的內容抓出來
target_sitename = ["中山", "林口", "中壢"] #目標區域
data = [] #空list 存過濾結果

#迴圈查詢目標區域，加入list作為輸出
for record in records:
    if record["sitename"] in target_sitename:
        data.append({
            "日期： ":record["monitordate"],
            "區域： ":record["sitename"],
            "AQI： ":record["aqi"]
        })

#資料轉換為表格並輸出為csv
df = pd.DataFrame(data)
df.to_csv("api.csv", index=False, encoding="utf-8-sig")
