# -*- coding: utf-8 -*-
"""static

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ckk-TAIEBqOBJM_oAmSh_AW2vS3PMc0u
"""

#導入模組
import requests
import pandas as pd
from bs4 import BeautifulSoup

#連接網站、獲取網頁內容
url = "https://airtw.moenv.gov.tw/cht/EnvMonitoring/Central/CentralMonitoring.aspx"
response = requests.get(url)

#解析html原始碼
soup = BeautifulSoup(response.text, "html.parser")

base_class = "bor-top-" #span class前綴
colors = ["green", "yellow", "orange", "red", "purple", "brown"] #span class後綴
data = [] #空list，存對應資料

#迴圈搜尋指標
for color in colors:
  class_name = base_class + color
  span = soup.find("span", class_=class_name) #搜尋對應class的span
  parts = span.contents #把span內容分段
  level = parts[0].strip() #危險等級
  range = parts[2].strip() #數值

  #資料加入list
  data.append({
      "等級： ": level,
      "對應數值： ": range
  })

#資料轉換為表格並輸出為csv
df = pd.DataFrame(data)
df.to_csv("static.csv", index=False, encoding="utf-8-sig")